// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojxncmydgspcxmtxosez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeG5jbXlkZ3NwY3htdHhvc2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjQ3MDMsImV4cCI6MjA2Mjc0MDcwM30.Mlei9UwNoYmbefINGbN5SFJoaC_1Ncr_9bReksCwJfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);